version: "3.9"
services:
  influxdb:
    image: "influxdb:2.0.7"
    ports:
      - "8086:8086"
    volumes:
      - "./volumes/influxdb/config/config.yml:/etc/influxdb2/config.yml"
      - "./volumes/influxdb/data:/var/lib/influxdb2"

  influxdb_cli:
    image: "influxdb:2.0.7"
    depends_on:
      - influxdb
    profiles:
      - influx_admin

  mosquitto:
    image: "eclipse-mosquitto:2.0.10"
    ports:
      - "1883:1883"
    volumes:
      - "./volumes/mosquitto/config:/mosquitto/config"
      - "./volumes/mosquitto/data:/mosquitto/data"
      - "./volumes/mosquitto/log:/mosquitto/log"

  telegraf:
    image: "telegraf:1.18"
    env_file:
      - telegraf-vars.env
    depends_on:
      - influxdb
      - mosquitto
    ports:
      - "8094:8094"
    volumes:
      - "./volumes/telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf"

  grafana:
    image: "grafana/grafana:8.0.5"
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/admin_password
      GF_RENDERING_SERVER_URL: http://grafana_renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    user: "${UID}:${GID}"
    volumes:
      - "./volumes/grafana/admin_password:/run/secrets/admin_password"
      - "./volumes/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./volumes/grafana/provisioning:/etc/grafana/provisioning"
      - "./volumes/grafana/data:/var/lib/grafana"

  grafana_renderer:
    image: "grafana/grafana-image-renderer:3.0.1"
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'
