{
 "title": "AlmaLinux Popularity",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Docker images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Docker Hub pulls",
   "type": "timeseries",
   "description": "Docker Hub image pulls statistics.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"distro_spread\")\n  |> filter(fn: (r) => r[\"platform\"] == \"dockerhub\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pulls\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"${r.org}/${r.image}\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Docker Hub Stars",
   "type": "timeseries",
   "description": "Docker Hub image stars statistics.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"distro_spread\")\n  |> filter(fn: (r) => r[\"platform\"] == \"dockerhub\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stars\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"${r.org}/${r.image}\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Cloud images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Vagrant Box downloads",
   "type": "timeseries",
   "description": "Vagrant Box downloads count.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"platform\"] == \"vagrantup\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pulls\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"${r.org}/${r.image}\"}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Social", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Chat.almalinux.org users",
   "type": "timeseries",
   "description": "Chat.almalinux.org user activity statistics.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alma_social\")\n  |> filter(fn: (r) => r[\"platform\"] == \"chat.almalinux.org\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Reddit active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alma_social\")\n  |> filter(fn: (r) => r[\"platform\"] == \"reddit\")\n  |> filter(fn: (r) => r[\"_field\"] == \"active_users\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Reddit total users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alma_social\")\n  |> filter(fn: (r) => r[\"platform\"] == \"reddit\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_users\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "GitHub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Migration tool stars",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alma_social\")\n  |> filter(fn: (r) => r[\"platform\"] == \"github\")\n  |> filter(fn: (r) => r[\"repo\"] == \"almalinux-deploy\" or r[\"repo\"] == \"rocky-tools\")\n  |> filter(fn: (r) => r[\"_field\"] == \"stars\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Migration tool forks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alma_social\")\n  |> filter(fn: (r) => r[\"platform\"] == \"github\")\n  |> filter(fn: (r) => r[\"repo\"] == \"almalinux-deploy\" or r[\"repo\"] == \"rocky-tools\")\n  |> filter(fn: (r) => r[\"_field\"] == \"forks\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Migration tool followers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alma_social\")\n  |> filter(fn: (r) => r[\"platform\"] == \"github\")\n  |> filter(fn: (r) => r[\"repo\"] == \"almalinux-deploy\" or r[\"repo\"] == \"rocky-tools\")\n  |> filter(fn: (r) => r[\"_field\"] == \"subscribers\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Migration tool open issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "query": "from(bucket: \"distro_spread\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alma_social\")\n  |> filter(fn: (r) => r[\"platform\"] == \"github\")\n  |> filter(fn: (r) => r[\"repo\"] == \"almalinux-deploy\" or r[\"repo\"] == \"rocky-tools\")\n  |> filter(fn: (r) => r[\"_field\"] == \"open_issues\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}